

services:
  traefik:

    image: traefik:v2.10
    container_name: "traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.traefik.service=traefik-svc"
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  connexion:
    image: marcosf2/dragon-core
    build:
      context: ./dragon-core
    volumes:
      - ${IMAGE_MAPPING_DIRECTORY}:${IMAGE_HOME_DIRECTORY}
    container_name: "dragon-core"
    environment:
      COMPOSE_PROJECT_NAME: dev
      IMAGE_HOME_DIRECTORY: ${IMAGE_HOME_DIRECTORY}
      HOST: ${HOST}
      LAIRS_DIRECTORY: ${LAIRS_DIRECTORY}
      RESOURCE_PATH: ${RESOURCE_PATH}
      USERS: ${USERS}
      API_URL_PREFIX: ${API_URL_PREFIX}
      URL_HOST: ${URL_HOST}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.connexion.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.services.connexion.loadbalancer.server.port=8000"


  nextjs:
    image: marcosf2/dragon-scales
    container_name: "dragon-scales"
    build:
      context: ./dragon-scales
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 192.168.1.0/24
    driver_opts:
      com.docker.network.driver.mtu: 1450
